# Generated by Django 2.1.5 on 2019-01-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=16, verbose_name='宠物类别')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='宠物类别的关键字')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.Category')),
            ],
        ),
    ]
