# Generated by Django 2.1.5 on 2019-01-21 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('official', '0001_initial'),
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.TextField(verbose_name='评论的内容')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞日期')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.TextField(verbose_name='日常动态')),
                ('img', models.ImageField(null=True, upload_to='upload/tweet/images')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('pl_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('transpond', models.IntegerField(default=0, verbose_name='转发数')),
                ('heart_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.Category', verbose_name='宠物科属')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.Keyword', verbose_name='宠物类别')),
            ],
        ),
        migrations.AddField(
            model_name='heart',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstate.Tweet', verbose_name='对应的动态'),
        ),
        migrations.AddField(
            model_name='heart',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='点赞者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstate.Tweet', verbose_name='对应的动态'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='评论者'),
        ),
    ]
