# Generated by Django 2.1.5 on 2019-01-21 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', error_messages={'required': '用户名不能为空'}, max_length=12, null=True)),
                ('password', models.CharField(error_messages={'required': '密码不能为空'}, max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='手机号格式不对吧！', regex='^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')])),
                ('img', models.ImageField(upload_to='upload/user_msg/images')),
                ('flower', models.TextField(default='', max_length=65535)),
                ('star', models.TextField(default='', max_length=65535)),
                ('cate', models.CharField(max_length=16, verbose_name='宠物科属')),
                ('key', models.CharField(max_length=16, verbose_name='宠物品种')),
            ],
        ),
    ]
